# Generated by Django 4.2.5 on 2023-10-16 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='movies.genre'),
            preserve_default=False,
        ),
    ]
